### ISSUE TITLE
F-string formatting - unmatched '[' in OllamaInstructorClient

### ISSUE THREAD

**Issue by DarkTeddie** [lennartpollvogt/ollama-instructor#12]
The following exception is being thrown when using `chat_completion` from OllamaInstructorClient and OllamaInstructorAsyncClient (ollama_instructor\ollama_instructor_client.py) 

![image](https://github.com/user-attachments/assets/3233140d-b140-417b-a47b-81f6d593e88c)

I was able to resolve this by changing the F-Srtring to use double quotes
![image](https://github.com/user-attachments/assets/cc9be5ae-35c7-4883-b39c-68e64fba648a)

after change: 
![image](https://github.com/user-attachments/assets/83275a14-5b83-41a9-ae77-0d6bbf9286d3)

**Comment by lennartpollvogt** [comment]
Fix is released with newest version v0.5.2.

Thanks for the issue! I will close it now
